openwisp/docker-openwisp

.env, Makefile, README.md, build.py, build/common/init_command.sh, build/common/openwisp/settings.py, build/openwisp_nginx/Dockerfile, docs/ENV.md
Add basic documentation of variables
in docs/ENV.md.
Closes #31
=> [enchancement] Add documentation

README.md, build/openwisp_base/Dockerfile, docs/ENV.md
Small changes to documentation.
Closes #25
=> [minor/docs] Improve documentation

build/common/init_command.sh, build/common/openwisp/__init__.py, build/common/openwisp/celery.py, build/common/openwisp/settings.py, build/openwisp_base/Dockerfile, build/openwisp_dashboard/module_settings.py, build/openwisp_websocket/module_settings.py, docker-compose.yml, kubernetes/ReplicationController.yml, tests/tests.sh
=> [enhancement] Add celery image

README.md, docs/ENV.md, docs/FILES.md
Updated Gitter badge to point to docker-openwisp specific chat room.
=> [docs] Updated gitter badge

build/openwisp_base/Dockerfile, build/openwisp_controller/Dockerfile, build/openwisp_dashboard/Dockerfile, build/openwisp_radius/Dockerfile, build/openwisp_topology/Dockerfile
Changed the base image from alpine to debian
because we are having problems with alpine
like lack of version locking in `apk` package
manager.
Increases image size from 431MB to 553MB
=> [openwisp-base-image] Changed Image to debian

README.md
It's a pull request of documentation fix. Added more common description for the hosts file configuration, added name of option file.
Closes #70
=> [docs] Correct hosts file configuration guide 

README.md
=> [docs/minor] Improved according to feedback

build/openwisp_base/Dockerfile
Did temporary version locking to avoid
the containers failing every once in a while
because of update in some other repository
=> [chores] Temporary version locking

docker-compose.yml
Removed duplicated celery container from docker-compose.yml
Closes #80
=> [improvement] duplicated celery container#80

.travis.yml, build.py, build/common/openwisp/celery.py, build/common/openwisp/settings.py, build/common/openwisp/tasks.py, build/common/openwisp/utils.py, build/common/services.py, build/common/utils.py, build/openwisp_controller/module_settings.py, build/openwisp_dashboard/load_init_data.py, build/openwisp_dashboard/module_settings.py, build/openwisp_dashboard/urls.py, build/openwisp_radius/module_settings.py, build/openwisp_topology/module_settings.py, build/openwisp_websocket/module_settings.py, setup.cfg, tests/data.py, tests/runtests.py, tests/utils.py
**No functional changes, only formatting changes**
=> [qa] Reformatted code with black

.travis.yml, build.py, build/common/openwisp/celery.py, build/common/openwisp/settings.py, build/common/openwisp/tasks.py, build/common/openwisp/utils.py, build/common/services.py, build/common/utils.py, build/openwisp_controller/module_settings.py, build/openwisp_dashboard/load_init_data.py, build/openwisp_dashboard/module_settings.py, build/openwisp_dashboard/urls.py, build/openwisp_radius/module_settings.py, build/openwisp_topology/module_settings.py, build/openwisp_websocket/module_settings.py, setup.cfg, tests/data.py, tests/runtests.py, tests/utils.py
=>  [improvement] Removed unnecessarily registered admin

Makefile, README.md, docs/QUICK_SETUP.md, tests/runtests.py
=> [enchancement] Using docker-compose in production

README.md, build/common/openwisp/settings.py, build/openwisp_base/Dockerfile, build/openwisp_dashboard/module_settings.py, build/openwisp_freeradius/raddb/mods-available/sqlcounter, build/openwisp_radius/module_settings.py, build/openwisp_radius/urls.py
=> [gsoc2020] Removed django-freeradius #133

.travis.yml
=> [improvement] Introduce Travis-buddy #130

build.py, build/common/openwisp/settings.py, build/common/services.py, build/common/utils.py, tests/runtests.py, tests/utils.py
=> [improvements] Reformat strings to use f-strings #107

Makefile, README.md
=> [registry] Use GitLab registry

.github/workflows/branch.yml, .github/workflows/pull_request.yml, README.md
Pushing automatically was not working, fixed it. :smile:
=> [ci] Publish images from GitHub-CI

build/openwisp_dashboard/load_init_data.py
=> [bug] When org name is changed, restarting images shouldn't fail #145

.github/workflows/branch.yml, .github/workflows/pull_request.yml, Makefile, auto-install.sh, tests/utils.py
Previously, the latest version of docker-compose.yml from github was used, which is not ideal because if the file is changed, auto installing the older versions becomes harder.
So, now the version is picked from tag (+ minor improvements)
=> [enhancement] Specific version auto-install script 

.github/workflows/branch.yml, .github/workflows/pull_request.yml
Minor PR to remove version lock for stable stable during testing.
=> [qa] Removed chrome-stable version lock

.env, README.md, build/common/openwisp/settings.py, build/common/utils.sh, build/openwisp_api/module_settings.py, build/openwisp_api/urls.py, build/openwisp_base/Dockerfile, build/openwisp_dashboard/module_settings.py, docker-compose.yml, docs/ENV.md
TODO:
Closes #139
Blocked https://github.com/openwisp/openwisp-monitoring/pull/304
=> [enchancement] Add monitoring image #139

auto-install.sh
Fixing the docker-compose install issue with fix inspired from here - https://github.com/MISP/misp-docker/issues/113
=> [autoinstall] docker-compose install fix #172

README.md, deploy/auto-install.sh
=> [autoinstall] Upgrade feature added

build/openwisp_api/urls.py
=> [enchancement] Add users API and swagger endpoint

build/common/utils.sh, build/openwisp_nginx/Dockerfile
=> [nginx] Fix certbot cronjob handling Fixes #179

build/common/uwsgi.conf.ini
=> [fix] Fix uwsgi OSerror #185

build/openwisp_nginx/nginx.template.conf
=> [change] Disabled nginx server_tokens

build/common/openwisp/settings.py, build/openwisp_base/Dockerfile, build/openwisp_dashboard/module_settings.py, requirements-test.txt
- Implemented `static minification` and `cache invalidation `
Closes #187
=> [feature] Implemented static minification and cache invalidation #187

build/openwisp_dashboard/module_settings.py, build/openwisp_radius/module_settings.py
Needed for https://github.com/openwisp/openwisp-radius/pull/394 .
=> [change] Added django.contrib.humanize

build/common/utils.sh, build/openwisp_api/Dockerfile, build/openwisp_base/Dockerfile, build/openwisp_base/requirements.txt, build/openwisp_dashboard/Dockerfile, build/openwisp_dashboard/openvpn.json, build/openwisp_freeradius/Dockerfile, build/openwisp_freeradius/raddb/mods-enabled/sql, build/openwisp_freeradius/raddb/radiusd.conf, build/openwisp_websocket/Dockerfile, build/openwisp_websocket/daphne.conf
Work in progress, not ready yet, but functional.
Will close #109
=> [change] Create dedicated openwisp user #109

README.md
=> [docs] Updated runtests instructions

docs/ENV.md, images/common/openwisp/settings.py, images/common/services.py
Allow specifying redis port and password.
=> [feature] Allow specifying redis port and password

images/openwisp_freeradius/Dockerfile
Not sure why it broke on its own all of a sudden! Suggestions are welcome.
Fixes #234
=> [fix] Fixed broken freeradius image #234

images/openwisp_base/requirements.txt
=> [feature] Added django-storage and boto3 in openwisp-base image #233

docker-compose.yml
My containers somehow get killed with error 137, this workarounds it and restarts them.
=> docker compose: always restart containers

images/common/utils.py, tests/config.json
It was not possible to use uwsgi_curl for URLs, e.g.:
http://127.0.0.1:8000/admin
=> [fix] Fixed uwsgi_curl

images/openwisp_base/Dockerfile
Resolves issue https://github.com/openwisp/docker-openwisp/issues/254
=> lowercase stage name for openwisp base image

images/common/utils.sh, images/openwisp_base/Dockerfile, images/openwisp_dashboard/module_settings.py, images/openwisp_freeradius/Dockerfile, images/openwisp_nfs/Dockerfile, images/openwisp_nginx/Dockerfile, images/openwisp_openvpn/Dockerfile, images/openwisp_postfix/Dockerfile, tests/runtests.py, tests/utils.py
This PR fixes:
- `openwisp-freeradius`
- `openwisp-postifix`
- `openwisp-nginx`
- `openwisp-dashboard` (mainly autocomplete filter errors)
- Docker tests and QA checks
=> [fix] Fixed docker-openwisp installation

deploy/examples/kubernetes/Deployment.yml, docker-compose.yml, images/common/openwisp/settings.py, images/openwisp_base/Dockerfile
Added the missing firmware image private storage directory to the volume mounts.
Fixes #270
=> [fix] Fixed firmware private storage missing dir #270

.github/workflows/branch.yml, .github/workflows/pull_request.yml, deploy/auto-install.sh
=> [feature] Added support for Ubuntu 22 #279

images/openwisp_base/Dockerfile
=> [change] Removed gcc from base image #222

deploy/auto-install.sh, docs/user/customization.rst, docs/user/kubernetes.rst, docs/user/settings.rst, images/common/openwisp/settings.py, images/common/utils.sh, images/openwisp_nginx/openwisp.ssl.template.conf, tests/utils.py
using a list of typo regex from the English Wikipedia https://en.wikipedia.org/w/index.php?title=Wikipedia:AutoWikiBrowser/Typos&action=raw
=> fix common typos

.github/workflows/pull_request.yml, Makefile, README.md, deploy/auto-install.sh, docker-compose.yml, docs/ENV.md, docs/FAQ.md, docs/QUICK_SETUP.md, images/openwisp_base/Dockerfile, requirements-test.txt, tests/runtests.py, tests/utils.py
Migrate to Docker Compose v2.
Related to #299.
=> [change] Migrate to Docker Compose v2

.github/workflows/ci.yml
- Added steps in GitHub Action to test the upgrade operation of auto-install script
=> [ci] Fixed CI to run on push to master branch

images/common/openwisp/settings.py, images/openwisp_nginx/openwisp.ssl.template.conf, tests/utils.py
Fixed build issues appeared after the last general upgrade of the docs and other details.
=> [fix] Fix build issues appeared after restructuring

deploy/auto-install.sh
Closes #343
I removed the upgrade to pip and I added 12 to the supported versions
=> Update auto-install.sh to support Debian 12

docs/user/settings.rst
Required for https://github.com/openwisp/openwisp-docs/pull/206
=> [docs] Fixed RADIUS module reference

docker-compose.yml, docs/user/settings.rst, images/common/init_command.sh, images/common/utils.sh, images/openwisp_dashboard/load_init_data.py, images/openwisp_dashboard/openvpn.json, images/openwisp_openvpn/Dockerfile, images/openwisp_openvpn/send-topology.sh, tests/runtests.py
=> [feature] Added topology for the default VPN #99

.env, docker-compose.yml, docs/user/settings.rst, images/common/init_command.sh, images/common/utils.sh, images/openwisp_base/Dockerfile, images/openwisp_dashboard/load_init_data.py, images/openwisp_dashboard/openvpn.json, images/openwisp_nginx/Dockerfile, images/openwisp_openvpn/Dockerfile, images/openwisp_openvpn/send-topology.sh, tests/runtests.py
- Allowed celery containers to reach devices
- Added health check for OpenVPN service
Closes #335
=> [feature] Added default credentials and SSH key template #335

.github/workflows/release.yml, Makefile
Please [open a new issue](https://github.com/openwisp/docker-openwisp/issues/new/choose) if there isn't an existing issue yet.
Added workflow for tagging images with version on release
Closes #351
=> [change] Updated Makefile to use "edge" label by default #351

images/openwisp_api/urls.py
=> [fix] Added admin URLs to the API container

images/common/init_command.sh, images/common/utils.sh, images/openwisp_openvpn/openvpn.sh, images/openwisp_openvpn/revokelist.sh
=> [fix] Fixed OpenVPN restarting every minute and outdated revokelist #377 #378

CHANGES.rst
24.11.0 release
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 24.11.0 release

.github/workflows/ci.yml, docker-compose.yml
=> [fix] Added "/dev/net/tun" to OpenVPN service

images/openwisp_postfix/Dockerfile
=> [deps] Bumped postfix~=3.9.1-r0

.github/workflows/ci.yml, deploy/auto-install.sh, tests/runtests.py
=> [fix] Allow auto-install script to install from forked repository

.github/workflows/ci.yml, CHANGES.rst, Makefile, deploy/auto-install.sh, docker-compose.yml, images/common/openwisp/__init__.py
Signed-off-by: Gagan Deep <pandafy.dev@gmail.com>
=> 24.11.2 release

deploy/auto-install.sh
=> [fix] Suggest correct vpn hostname in auto-install script

images/openwisp_postfix/Dockerfile
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
=> [deps] Bump postfix from ~=postfix-3.9.3-r0 to ~=postfix-3.9.4-r0

images/common/openwisp/__init__.py, images/common/openwisp/routing.py, images/common/openwisp/settings.py, images/openwisp_base/Dockerfile, images/openwisp_dashboard/module_settings.py
=> [chores] Migrated to Django 4.2+ STORAGES setting #442

images/openwisp_nginx/Dockerfile, images/openwisp_nginx/openwisp.ssl.template.conf, images/openwisp_postfix/Dockerfile
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
=> [deps] Bumped openssl from ~=3.5.2-r0 to ~=3.5.3-r1

images/openwisp_nginx/Dockerfile, images/openwisp_postfix/Dockerfile
I just updated this a few days ago and it was yanked again.
It's too unstable to keep pinned, it breaks the build too often and is driving me mad.
=> [deps] Unpinned openssl
